export const currencies = [
  { value: 'aed', label: 'AED (د.إ) - UAE Dirham' },
  { value: 'ars', label: 'ARS ($) - Argentine Peso' },
  { value: 'aud', label: 'AUD (A$) - Australian Dollar' },
  { value: 'brl', label: 'BRL (R$) - Brazilian Real' },
  { value: 'cad', label: 'CAD (C$) - Canadian Dollar' },
  { value: 'chf', label: 'CHF (Fr) - Swiss Franc' },
  { value: 'clp', label: 'CLP ($) - Chilean Peso' },
  { value: 'cny', label: 'CNY (¥) - Chinese Yuan' },
  { value: 'cop', label: 'COP ($) - Colombian Peso' },
  { value: 'czk', label: 'CZK (Kč) - Czech Koruna' },
  { value: 'dkk', label: 'DKK (kr) - Danish Krone' },
  { value: 'egp', label: 'EGP (E£) - Egyptian Pound' },
  { value: 'eur', label: 'EUR (€) - Euro' },
  { value: 'gbp', label: 'GBP (£) - British Pound' },
  { value: 'hkd', label: 'HKD (HK$) - Hong Kong Dollar' },
  { value: 'huf', label: 'HUF (Ft) - Hungarian Forint' },
  { value: 'idr', label: 'IDR (Rp) - Indonesian Rupiah' },
  { value: 'ils', label: 'ILS (₪) - Israeli New Shekel' },
  { value: 'inr', label: 'INR (₹) - Indian Rupee' },
  { value: 'jpy', label: 'JPY (¥) - Japanese Yen' },
  { value: 'krw', label: 'KRW (₩) - South Korean Won' },
  { value: 'lkr', label: 'LKR (රු) - Sri Lankan Rupee' },
  { value: 'mxn', label: 'MXN ($) - Mexican Peso' },
  { value: 'myr', label: 'MYR (RM) - Malaysian Ringgit' },
  { value: 'ngn', label: 'NGN (₦) - Nigerian Naira' },
  { value: 'nok', label: 'NOK (kr) - Norwegian Krone' },
  { value: 'nzd', label: 'NZD ($) - New Zealand Dollar' },
  { value: 'php', label: 'PHP (₱) - Philippine Peso' },
  { value: 'pln', label: 'PLN (zł) - Polish Złoty' },
  { value: 'rub', label: 'RUB (₽) - Russian Ruble' },
  { value: 'sek', label: 'SEK (kr) - Swedish Krona' },
  { value: 'sgd', label: 'SGD (S$) - Singapore Dollar' },
  { value: 'thb', label: 'THB (฿) - Thai Baht' },
  { value: 'try', label: 'TRY (₺) - Turkish Lira' },
  { value: 'usd', label: 'USD ($) - US Dollar' },
  { value: 'vnd', label: 'VND (₫) - Vietnamese Đồng' },
  { value: 'zar', label: 'ZAR (R) - South African Rand' },
];
